import { LLMProviderInfo } from "@brand-os/shared";

export class LLMProviderRegistry {
  private providers: LLMProviderInfo[] = [
    {
      provider: "OpenAI",
      model: "gpt-4o",
      releaseDate: "2024-05-13",
      contextWindow: 128000,
      inputPricingPer1M: 2.50,
      outputPricingPer1M: 10.00,
      modalities: ["text", "vision", "audio"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: true,
      audio: true,
      codingScore: 92,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://platform.openai.com/docs/models",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "OpenAI",
      model: "o3-mini",
      releaseDate: "2025-01-31",
      contextWindow: 200000,
      inputPricingPer1M: 1.10,
      outputPricingPer1M: 4.40,
      modalities: ["text"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 96,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://openai.com/index/openai-o3-mini/",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "Anthropic",
      model: "claude-3-5-sonnet",
      releaseDate: "2024-10-22",
      contextWindow: 200000,
      inputPricingPer1M: 3.00,
      outputPricingPer1M: 15.00,
      modalities: ["text", "vision"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: true,
      audio: false,
      codingScore: 97,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://docs.anthropic.com/en/docs/models-overview",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "Google",
      model: "gemini-1.5-pro",
      releaseDate: "2024-05-24",
      contextWindow: 2000000,
      inputPricingPer1M: 1.25,
      outputPricingPer1M: 5.00,
      modalities: ["text", "vision", "audio", "video"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: true,
      audio: true,
      codingScore: 90,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://ai.google.dev/gemini-api/docs/models/gemini",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "xAI",
      model: "grok-2",
      releaseDate: "2024-08-13",
      contextWindow: 128000,
      inputPricingPer1M: 2.00,
      outputPricingPer1M: 10.00,
      modalities: ["text", "vision"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: true,
      audio: false,
      codingScore: 89,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://x.ai/api",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "Groq",
      model: "llama-3.3-70b-versatile",
      releaseDate: "2024-12-06",
      contextWindow: 128000,
      inputPricingPer1M: 0.59,
      outputPricingPer1M: 0.79,
      modalities: ["text"],
      reasoning: false,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 88,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://groq.com",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "DeepSeek",
      model: "deepseek-r1",
      releaseDate: "2025-01-20",
      contextWindow: 64000,
      inputPricingPer1M: 0.55,
      outputPricingPer1M: 2.19,
      modalities: ["text"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 98,
      availability: "OPEN_WEIGHTS",
      status: "ACTIVE",
      officialSource: "https://github.com/deepseek-ai/DeepSeek-R1",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "Alibaba Qwen",
      model: "qwen-2.5-coder-32b",
      releaseDate: "2024-11-12",
      contextWindow: 128000,
      inputPricingPer1M: 0.30,
      outputPricingPer1M: 0.90,
      modalities: ["text"],
      reasoning: false,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 94,
      availability: "OPEN_WEIGHTS",
      status: "ACTIVE",
      officialSource: "https://github.com/QwenLM/Qwen2.5-Coder",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "Meta",
      model: "llama-3.3-70b-instruct",
      releaseDate: "2024-12-06",
      contextWindow: 128000,
      inputPricingPer1M: 0.00,
      outputPricingPer1M: 0.00,
      modalities: ["text"],
      reasoning: false,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 88,
      availability: "OPEN_WEIGHTS",
      status: "ACTIVE",
      officialSource: "https://www.llama.com",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "Mistral",
      model: "mistral-large-2411",
      releaseDate: "2024-11-18",
      contextWindow: 128000,
      inputPricingPer1M: 2.00,
      outputPricingPer1M: 6.00,
      modalities: ["text"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 91,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://docs.mistral.ai",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "Ollama",
      model: "ollama/llama3.3:latest",
      releaseDate: "2024-12-10",
      contextWindow: 128000,
      inputPricingPer1M: 0.00,
      outputPricingPer1M: 0.00,
      modalities: ["text"],
      reasoning: false,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 88,
      availability: "LOCAL_ONLY",
      status: "ACTIVE",
      officialSource: "https://ollama.com/library/llama3.3",
      lastVerified: "2026-08-08T00:00:00Z",
    },
    {
      provider: "NVIDIA",
      model: "nvidia/llama-3.1-nemotron-70b-instruct",
      releaseDate: "2024-10-15",
      contextWindow: 128000,
      inputPricingPer1M: 0.35,
      outputPricingPer1M: 0.70,
      modalities: ["text"],
      reasoning: true,
      toolCalling: true,
      structuredOutput: true,
      vision: false,
      audio: false,
      codingScore: 93,
      availability: "PUBLIC_API",
      status: "ACTIVE",
      officialSource: "https://build.nvidia.com",
      lastVerified: "2026-08-08T00:00:00Z",
    },
  ];

  public getAllProviders(): LLMProviderInfo[] {
    return this.providers;
  }

  public getByProvider(providerName: string): LLMProviderInfo[] {
    return this.providers.filter(
      (p) => p.provider.toLowerCase() === providerName.toLowerCase()
    );
  }

  public getBestModelForTask(taskType: "coding" | "reasoning" | "cost" | "context"): LLMProviderInfo {
    const sorted = [...this.providers];
    if (taskType === "coding") {
      sorted.sort((a, b) => b.codingScore - a.codingScore);
    } else if (taskType === "reasoning") {
      sorted.sort((a, b) => (b.reasoning ? 1 : 0) - (a.reasoning ? 1 : 0));
    } else if (taskType === "cost") {
      sorted.sort((a, b) => a.inputPricingPer1M - b.inputPricingPer1M);
    } else if (taskType === "context") {
      sorted.sort((a, b) => b.contextWindow - a.contextWindow);
    }
    return sorted[0];
  }
}

export const llmProviderRegistry = new LLMProviderRegistry();
