import { Request, Response } from "express";
import { TrendDiscoveryAgent } from "@brand-os/agents";
import { aiGateway } from "@brand-os/ai-gateway";
import { RoutingStrategy } from "@brand-os/shared";

export class TrendsController {
  public async getTrends(_req: Request, res: Response) {
    const trendAgent = new TrendDiscoveryAgent();
    const trendRes = await trendAgent.run();
    const topics = trendRes.data || [];
    res.json({ topics });
  }

  public async scanTrends(_req: Request, res: Response) {
    const trendAgent = new TrendDiscoveryAgent();
    const trendRes = await trendAgent.run();
    const topics = trendRes.data || [];
    res.json({ success: true, count: topics.length, topics });
  }

  public async generateCustomTrend(req: Request, res: Response): Promise<void> {
    const { prompt } = req.body;
    if (!prompt) {
      res.status(400).json({ error: "Prompt is required" });
      return;
    }

    try {
      const aiResponse = await aiGateway.execute({
        prompt: `Generate a structured tech topic card object for the custom topic idea: "${prompt}".
Respond ONLY with a valid JSON object matching this schema:
{
  "id": "top_custom_${Date.now()}",
  "title": "Compelling Title",
  "category": "Tech Category",
  "score": 96,
  "reason": "Why this topic is highly relevant for tech leads right now",
  "trend_velocity": 9.5,
  "difficulty": "ADVANCED",
  "competition": "MEDIUM",
  "audience": "Software Engineers & Tech Leads",
  "keywords": ["tag1", "tag2", "tag3"],
  "references": ["https://github.com"]
}`,
        taskType: "trend_discovery",
        temperature: 0.7,
        routingStrategy: RoutingStrategy.COST_OPTIMIZED,
      });

      const jsonMatch = aiResponse.text.match(/\{[\s\S]*\}/);
      let topicObj = null;
      if (jsonMatch) {
        topicObj = JSON.parse(jsonMatch[0]);
      }

      if (!topicObj) {
        topicObj = {
          id: `top_custom_${Date.now()}`,
          title: prompt.length > 50 ? prompt : `${prompt}: Production Architecture & Implementation Patterns`,
          category: "Custom Topic",
          score: 95,
          reason: `Generated by AI Copilot for targeted execution: ${prompt}`,
          trend_velocity: 9.4,
          difficulty: "INTERMEDIATE",
          competition: "LOW",
          audience: "Staff Engineers & Architects",
          keywords: prompt.split(" ").slice(0, 4),
          references: ["https://github.com"],
        };
      }

      res.json({ success: true, topic: topicObj });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  }
}

export const trendsController = new TrendsController();
